name: confwebsite2022
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_svg_provider: ^1.0.3
  gap: ^2.0.0
  go_router: ^3.1.1
  google_fonts:
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  styled_text: ^5.0.0+1
  transparent_image:
    git:
      url: https://github.com/jiyuujin/transparent_image
      ref: bugfix/bitmap-test

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  url_launcher: ^6.0.20

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/photo/
